spring:
  application:
    name: dev


  ### mysql

  datasource:
    url: jdbc:mysql://localhost:3306/bomc?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

    ### oracle

    #  datasource:
    #    url: jdbc:oracle:thin:@bomc-db:1521:root
    #    username: root
    #    password: root
    #    driver-class-name: oracle.jdbc.driver.OracleDriver

server:
  port: 25590
  servlet:
    context-path: /ai


mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml






